package com.transvoice.keyboard;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public class SettingsActivity extends Activity{
 SharedPreferences p; LinearLayout root;
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("prefs",0);build();if(getIntent().getBooleanExtra("request_mic",false)&&Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.RECORD_AUDIO")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.RECORD_AUDIO"},900);}
 TextView title(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(19);t.setTextColor(Color.rgb(20,20,20));t.setPadding(0,26,0,8);return t;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,28);ScrollView sc=new ScrollView(this);sc.addView(root);setContentView(sc);TextView h=new TextView(this);h.setText("TransVoice Keyboard");h.setTextSize(28);h.setTextColor(Color.rgb(20,20,20));root.addView(h);
  root.addView(title("Appearance"));RadioGroup g=new RadioGroup(this);String[]ls={"System Default","Light","Dark"};String[]vs={"system","light","dark"};for(int i=0;i<3;i++){RadioButton r=new RadioButton(this);r.setText(ls[i]);r.setTag(vs[i]);r.setTextSize(16);r.setChecked(p.getString("theme","system").equals(vs[i]));g.addView(r);}g.setOnCheckedChangeListener((x,id)->{RadioButton r=x.findViewById(id);if(r!=null)p.edit().putString("theme",(String)r.getTag()).apply();});root.addView(g);
  root.addView(title("Translation"));CheckBox preview=new CheckBox(this);preview.setText("Preview translation before inserting");preview.setChecked(p.getBoolean("preview",false));preview.setOnCheckedChangeListener((b,v)->p.edit().putBoolean("preview",v).apply());root.addView(preview);
  root.addView(title("Languages"));Button in=button("Speak language: "+label(p.getString("input_lang","ta-IN")));in.setOnClickListener(v->choose(true,in));root.addView(in);Button out=button("Text language: "+label(p.getString("output_lang","en-US")));out.setOnClickListener(v->choose(false,out));root.addView(out);Button swap=button("⇄ Swap languages");swap.setOnClickListener(v->{String a=p.getString("input_lang","ta-IN"),bb=p.getString("output_lang","en-US");p.edit().putString("input_lang",bb).putString("output_lang",a).apply();in.setText("Speak language: "+label(bb));out.setText("Text language: "+label(a));});root.addView(swap);
  root.addView(title("Privacy"));TextView privacy=new TextView(this);privacy.setText("Voice recordings are not stored by TransVoice Keyboard. Speech recognition and translation may use device/Google services depending on availability. Translation models are downloaded on demand by ML Kit. Internet access may be required for first-time model downloads.");privacy.setTextSize(14);root.addView(privacy);
  root.addView(title("About"));TextView about=new TextView(this);about.setText("Version 1.0.2\nCustom Android IME with multilingual speech-to-text and on-device ML Kit translation.");about.setTextSize(14);root.addView(about);
 }
 Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 String label(String c){for(TransVoiceImeService.Lang l:TransVoiceImeService.LANGS)if(l.locale.equals(c))return l.label();return c;}
 void choose(boolean input,Button b){String[]names=new String[TransVoiceImeService.LANGS.length];for(int i=0;i<names.length;i++)names[i]=TransVoiceImeService.LANGS[i].label();String cur=p.getString(input?"input_lang":"output_lang",input?"ta-IN":"en-US");int ck=0;for(int i=0;i<names.length;i++)if(TransVoiceImeService.LANGS[i].locale.equals(cur))ck=i;new AlertDialog.Builder(this).setTitle(input?"Speak language":"Text language").setSingleChoiceItems(names,ck,(d,w)->{String loc=TransVoiceImeService.LANGS[w].locale;p.edit().putString(input?"input_lang":"output_lang",loc).apply();b.setText((input?"Speak language: ":"Text language: ")+names[w]);d.dismiss();}).setNeutralButton("Search",null).show();}
}
