package com.transvoice.keyboard;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.inputmethodservice.InputMethodService;
import android.os.*;
import android.speech.*;
import android.view.*;
import android.view.inputmethod.*;
import android.widget.*;
import com.google.mlkit.common.model.DownloadConditions;
import com.google.mlkit.nl.translate.*;
import java.util.*;

public class TransVoiceImeService extends InputMethodService {
    private KeyboardView keyboard; private InputConnection ic; private SharedPreferences prefs;
    static final String PREFS="prefs";
    @Override public void onCreate(){super.onCreate(); prefs=getSharedPreferences(PREFS,MODE_PRIVATE);}
    @Override public View onCreateInputView(){keyboard=new KeyboardView(this);return keyboard;}
    @Override public void onStartInput(EditorInfo info, boolean restarting){super.onStartInput(info,restarting);ic=getCurrentInputConnection();if(keyboard!=null)keyboard.invalidate();}
    void insert(String s){if(ic!=null&&s!=null)ic.commitText(s,1);}
    void backspace(){if(ic==null)return;CharSequence sel=ic.getSelectedText(0);if(sel!=null&&sel.length()>0){ic.commitText("",1);return;}CharSequence b=ic.getTextBeforeCursor(2,0);if(b!=null&&b.length()>0){if(Build.VERSION.SDK_INT>=24)ic.deleteSurroundingTextInCodePoints(1,0);else ic.deleteSurroundingText(1,0);}}
    void enter(){if(ic==null)return;EditorInfo info=getCurrentInputEditorInfo();int a=info!=null?(info.imeOptions&EditorInfo.IME_MASK_ACTION):EditorInfo.IME_ACTION_NONE;if(a!=EditorInfo.IME_ACTION_NONE&&a!=EditorInfo.IME_ACTION_UNSPECIFIED)ic.performEditorAction(a);else{ic.sendKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_ENTER));ic.sendKeyEvent(new KeyEvent(KeyEvent.ACTION_UP,KeyEvent.KEYCODE_ENTER));}}
    void settings(){Intent i=new Intent(this,SettingsActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);}

    static class Lang{String name,code,locale,flag,ml;Lang(String n,String c,String loc,String f,String m){name=n;code=c;locale=loc;flag=f;ml=m;}String label(){return flag+"  "+name;}}
    static final Lang[] LANGS=new Lang[]{
      new Lang("Tamil (தமிழ்)","ta","ta-IN","🇮🇳","ta"),new Lang("English (US)","en","en-US","🇺🇸","en"),new Lang("English (UK)","en","en-GB","🇬🇧","en"),
      new Lang("Hindi (हिन्दी)","hi","hi-IN","🇮🇳","hi"),new Lang("Telugu (తెలుగు)","te","te-IN","🇮🇳","te"),
      new Lang("Kannada (ಕನ್ನಡ)","kn","kn-IN","🇮🇳","kn"),new Lang("Bengali (বাংলা)","bn","bn-IN","🇮🇳","bn"),new Lang("Marathi (मराठी)","mr","mr-IN","🇮🇳","mr"),
      new Lang("Gujarati (ગુજરાતી)","gu","gu-IN","🇮🇳","gu"),new Lang("Mandarin Chinese","zh","zh-CN","🇨🇳","zh"),
      new Lang("Standard Arabic","ar","ar-SA","🇸🇦","ar"),new Lang("Portuguese (Brazil)","pt","pt-BR","🇧🇷","pt"),new Lang("Russian","ru","ru-RU","🇷🇺","ru"),
      new Lang("Indonesian","id","id-ID","🇮🇩","id"),new Lang("Korean (한국어)","ko","ko-KR","🇰🇷","ko"),new Lang("Spanish","es","es-ES","🇪🇸","es"),
    };
    Lang findLang(String code){for(Lang l:LANGS)if(l.code.equals(code)&&(!code.equals("en")||l.locale.equals(prefs.getString("input_lang","en-US"))||l.locale.equals(prefs.getString("output_lang","en-US"))))return l;return LANGS[0];}
    Lang findExact(String locale){for(Lang l:LANGS)if(l.locale.equals(locale))return l;return LANGS[0];}
    String inLocale(){return prefs.getString("input_lang","ta-IN");} String outLocale(){return prefs.getString("output_lang","en-US");}
    String mlCode(String locale){return findExact(locale).ml;}
    boolean sameLang(){return findExact(inLocale()).code.equals(findExact(outLocale()).code);}

    void remember(String locale){LinkedHashSet<String>s=new LinkedHashSet<>();String r=prefs.getString("recent","");if(!r.isEmpty())s.addAll(Arrays.asList(r.split(",")));s.add(locale);while(s.size()>8)s.remove(s.iterator().next());StringBuilder b=new StringBuilder();for(String x:s){if(b.length()>0)b.append(',');b.append(x);}prefs.edit().putString("recent",b.toString()).apply();}
    void swap(){String a=inLocale(),b=outLocale();prefs.edit().putString("input_lang",b).putString("output_lang",a).apply();if(keyboard!=null)keyboard.invalidate();}
    void chooseLang(boolean input){final String current=input?inLocale():outLocale(); final EditText search=new EditText(this);search.setHint("Search languages"); LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(24,0,24,0);box.addView(search);ListView list=new ListView(this);box.addView(list,new LinearLayout.LayoutParams(-1,0,1));AlertDialog d=new AlertDialog.Builder(this).setTitle(input?"Speak language":"Text language").setView(box).create();
      Runnable update=()->{String q=search.getText().toString().toLowerCase(Locale.ROOT);ArrayList<Lang> a=new ArrayList<>();for(Lang l:LANGS)if(l.name.toLowerCase(Locale.ROOT).contains(q))a.add(l);String[] labels=new String[a.size()];for(int i=0;i<a.size();i++)labels[i]=a.get(i).label();list.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,labels));list.setOnItemClickListener((p,v,pos,id)->{Lang l=a.get(pos);if(input)prefs.edit().putString("input_lang",l.locale).apply();else prefs.edit().putString("output_lang",l.locale).apply();remember(l.locale);d.dismiss();if(keyboard!=null)keyboard.invalidate();});};search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){update.run();}public void afterTextChanged(android.text.Editable e){}});d.setOnShowListener(x->update.run());d.show();}

    void mic(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){Intent permission=new Intent(this,SettingsActivity.class);permission.putExtra("request_mic",true);permission.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(permission);toast("Allow microphone access, then return to the keyboard and tap the microphone again.");return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Speech recognition is unavailable on this device");return;}final SpeechRecognizer sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle p){keyboard.setListening(true);}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){keyboard.setMicLevel(r);}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){keyboard.setListening(false);}public void onPartialResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty())keyboard.setPartial(x.get(0));}public void onEvent(int t,Bundle b){}public void onError(int e){keyboard.setListening(false);keyboard.setPartial("");sr.destroy();toast("Couldn't recognize speech. Try again.");}public void onResults(Bundle b){keyboard.setListening(false);keyboard.setPartial("");ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String text=x!=null&&!x.isEmpty()?x.get(0):"";sr.destroy();if(text.isEmpty()){toast("No speech detected");return;}translateAndInsert(text);}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,inLocale());i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true);i.putExtra(RecognizerIntent.EXTRA_MAX_RESULTS,3);sr.startListening(i);}

    void translateAndInsert(String source){if(sameLang()){insert(source);return;}String sourceCode=mlCode(inLocale()),targetCode=mlCode(outLocale());TranslatorOptions opt=new TranslatorOptions.Builder().setSourceLanguage(sourceCode).setTargetLanguage(targetCode).build();Translator tr=Translation.getClient(opt);DownloadConditions cond=new DownloadConditions.Builder().build();keyboard.setWorking(true);tr.downloadModelIfNeeded(cond).addOnSuccessListener(v->tr.translate(source).addOnSuccessListener(result->{keyboard.setWorking(false);if(prefs.getBoolean("preview",false))showPreview(source,result,tr);else{insert(result);tr.close();}}).addOnFailureListener(e->{keyboard.setWorking(false);toast("Translation failed");insert(source);tr.close();})).addOnFailureListener(e->{keyboard.setWorking(false);toast("Translation model unavailable");insert(source);tr.close();});}
    void showPreview(String original,String result,Translator tr){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(30,8,30,8);TextView o=new TextView(this);o.setText("Original\n"+original);o.setTextSize(15);TextView r=new TextView(this);r.setText("Translation");r.setTextSize(14);EditText e=new EditText(this);e.setText(result);e.setSingleLine(false);box.addView(o);box.addView(r);box.addView(e);new AlertDialog.Builder(this).setTitle("Translation").setView(box).setNegativeButton("Cancel",(d,w)->tr.close()).setPositiveButton("Insert",(d,w)->{insert(e.getText().toString());tr.close();}).show();}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}

    GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
    class KeyboardView extends View{
      Paint p=new Paint(3);ArrayList<Key> keys=new ArrayList<>();Handler h=new Handler(Looper.getMainLooper());Key down;Runnable longRun;boolean longFired=false,listening=false,working=false;float micLevel;String partial="";int BG,KEY,FG,ACC=Color.rgb(22,139,255);boolean symbols=false,emoji=false,shift=false,caps=false;long lastShift=0;
      KeyboardView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
      void setListening(boolean b){listening=b;invalidate();}void setMicLevel(float x){micLevel=Math.max(0,Math.min(10,x));invalidate();}void setWorking(boolean b){working=b;invalidate();}void setPartial(String s){partial=s;invalidate();}
      void colors(){String t=prefs.getString("theme","system");boolean dark=t.equals("dark")||(t.equals("system")&&((getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES));BG=Color.parseColor(dark?"#0B1118":"#E9EDF2");KEY=Color.parseColor(dark?"#182431":"#FFFFFF");FG=Color.parseColor(dark?"#F5F7FA":"#171A1D");}
      protected void onDraw(Canvas c){colors();c.drawColor(BG);keys.clear();float y=8;drawToolbar(c,getWidth(),y);y+=52;drawSuggestions(c,getWidth(),y);y+=38;if(emoji)drawEmoji(c,getWidth(),y,getHeight());else if(symbols)drawSymbols(c,getWidth(),y,getHeight());else drawLetters(c,getWidth(),y,getHeight());}
      void text(Canvas c,String s,float x,float y,float sz,int col){p.setColor(col);p.setTextSize(sz);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT);c.drawText(s,x,y-(p.ascent()+p.descent())/2,p);}
      void rr(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);p.clearShadowLayer();c.drawRoundRect(l,t,r,b,rad,rad,p);}
      void drawToolbar(Canvas c,int w,float y){rr(c,8,y,w-8,y+48,KEY,14);text(c,"⚙",32,y+24,22,FG);text(c,findExact(inLocale()).label()+" ▼",w*.27f,y+24,13,FG);text(c,"⇄",w*.50f,y+24,22,FG);text(c,findExact(outLocale()).label()+" ▼",w*.73f,y+24,13,FG);text(c,working?"…":"✨",w-30,y+24,18,ACC);}
      void drawSuggestions(Canvas c,int w,float y){String[]s=partial.isEmpty()?new String[]{"I","The","I'm","You","What"}:new String[]{partial,"Translate","Insert","Edit","⌫"};float u=w/5f;for(int i=0;i<5;i++)text(c,s[i],u*i+u/2,y+17,14,FG);}
      void key(Canvas c,String lab,float l,float t,float r,float b,int action,int color){Key k=new Key(lab,l,t,r,b,action);keys.add(k);int col=color==0?KEY:color;if(down==k){}if(down!=null&&down.label.equals(lab)){col=color==0?(BG==Color.parseColor("#0B1118")?Color.rgb(34,50,66):Color.rgb(215,222,231)):color;l+=1.5;t+=1.5;r-=1.5;b-=1.5;}if(lab.equals("🎙")&&listening){p.setShadowLayer(16+micLevel*2,0,0,ACC);rr(c,l,t,r,b,ACC,24);p.clearShadowLayer();text(c,"●",(l+r)/2,(t+b)/2,10,Color.WHITE);}else if(lab.equals("🎙")&&working){rr(c,l,t,r,b,ACC,24);text(c,"…",(l+r)/2,(t+b)/2,18,Color.WHITE);}else text(c,lab,(l+r)/2,(t+b)/2,lab.equals("space")?15:(lab.length()>1?17:20),color!=0?Color.WHITE:FG);rr(c,l,t,r,b,col,10);if(!(lab.equals("🎙")&&(listening||working)))text(c,lab,(l+r)/2,(t+b)/2,lab.equals("space")?15:(lab.length()>1?17:20),color!=0?Color.WHITE:FG);}
      void rows(Canvas c,String[]a,float y,float h){float gap=5,cell=(getWidth()-gap*(a.length-1))/(float)a.length,x=0;for(String s:a){key(c,s,x,y,x+cell,y+h,0,0);x+=cell+gap;}}
      void drawLetters(Canvas c,int w,float y,float bottom){float row=43;rows(c,new String[]{"Q","W","E","R","T","Y","U","I","O","P"},y,row);rows(c,new String[]{"A","S","D","F","G","H","J","K","L"},y+48,row);rows(c,new String[]{"⇧","Z","X","C","V","B","N","M","⌫"},y+96,row);float by=y+144,bh=Math.max(42,Math.min(52,bottom-by-4)),gap=5;float[]ws={1.1f,.7f,1.0f,1.0f,4.4f,.7f,.9f};String[]ls={"?123",",","😀","🎙","space",".","↵"};float total=9.8f,u=(w-gap*6)/total,x=0;for(int i=0;i<ls.length;i++){float ww=u*ws[i];key(c,ls[i],x,by,x+ww,by+bh,0,(i==3||i==6)?ACC:0);x+=ww+gap;}}
      void drawSymbols(Canvas c,int w,float y,float bottom){String[][]rs={{"1","2","3","4","5","6","7","8","9","0"},{"@","#","$","_","&","-","+","(",")","/"},{"=","*","\"","'",":",";","!","?","⌫"}};for(int j=0;j<3;j++){float gap=5,cell=(w-gap*(rs[j].length-1))/(float)rs[j].length,x=0;for(String s:rs[j]){key(c,s,x,y+j*48,x+cell,y+j*48+43,0,0);x+=cell+gap;}}float by=y+144,bh=Math.max(42,Math.min(52,bottom-by-4)),gap=5;String[]ls={"ABC",",","#+=","space",".","↵"};float[]ws={1.1f,.7f,1f,4.2f,.7f,1.0f};float u=(w-gap*5)/8.7f,x=0;for(int i=0;i<ls.length;i++){float ww=u*ws[i];key(c,ls[i],x,by,x+ww,by+bh,i==0?1:0,i==5?ACC:0);x+=ww+gap;}}
      void drawEmoji(Canvas c,int w,float y,float bottom){String[]a={"😀","😂","🤣","😊","😍","🥰","😎","🤔","😭","😡","👍","👏","🙏","🔥","❤️","🎉","💯","✨","💪","😴","🎂","☀️","🌟","🚀","❤️","🤣","🥳","😇","🤩","😱"};float gap=7,cell=(w-gap*4)/5f;int n=0;for(int r=0;r<4;r++){for(int j=0;j<5;j++){String s=a[n++];key(c,s,j*(cell+gap),y+r*48,j*(cell+gap)+cell,y+r*48+43,0,0);}}float by=y+192,bh=Math.max(42,Math.min(52,bottom-by-4));key(c,"ABC",8,by,88,by+bh,1,0);key(c,"space",94,by,w-88,by+bh,0,0);key(c,"↵",w-80,by,w-8,by+bh,0,ACC);}
      Key find(float x,float y){for(Key k:keys)if(x>=k.l&&x<=k.r&&y>=k.t&&y<=k.b)return k;return null;}
      void preview(Key k){if(k.label.length()>1)return;PopupWindow pw=new PopupWindow(TransVoiceImeService.this);TextView t=new TextView(TransVoiceImeService.this);t.setText(k.label);t.setTextSize(30);t.setGravity(Gravity.CENTER);t.setTextColor(FG);t.setBackground(bg(KEY,16));pw.setContentView(t);pw.setWidth(70);pw.setHeight(80);pw.setBackgroundDrawable(bg(KEY,16));pw.setFocusable(false);pw.showAtLocation(this,Gravity.TOP,(int)Math.max(0,getWidth()/2-35),(int)Math.max(10,k.t-85));h.postDelayed(pw::dismiss,300);}
      public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){if(y>=8&&y<=60){if(x<65){settings();return true;}if(x>getWidth()*.12&&x<getWidth()*.40){chooseLang(true);return true;}if(x>getWidth()*.42&&x<getWidth()*.58){swap();return true;}if(x>getWidth()*.60&&x<getWidth()*.88){chooseLang(false);return true;}}down=find(x,y);longFired=false;if(down!=null){preview(down);longRun=()->{longFired=true;if(down.label.equals("🎙"))micMenu();else if(down.label.equals("⌫"))repeatDelete();else if(down.label.equals("😀"))emoji=true;invalidate();};h.postDelayed(longRun,500);}return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(longRun!=null)h.removeCallbacks(longRun);Key k=find(x,y);if(k!=null&&k==down&&!longFired)press(k);down=null;invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_CANCEL){if(longRun!=null)h.removeCallbacks(longRun);down=null;invalidate();}return true;}
      void repeatDelete(){backspace();h.postDelayed(new Runnable(){public void run(){if(down!=null&&down.label.equals("⌫")){backspace();h.postDelayed(this,70);}}},70);}
      void micMenu(){new AlertDialog.Builder(TransVoiceImeService.this).setTitle("Voice input").setItems(new String[]{"Translate & Type","Speak → Same Language","Voice Settings"},(d,w)->{if(w==0)mic();else if(w==1){String old=inLocale();prefs.edit().putString("output_lang",old).apply();mic();}else settings();}).show();}
      void press(Key k){String s=k.label;if(s.equals("?123")){symbols=true;emoji=false;}else if(s.equals("ABC")){symbols=false;emoji=false;}else if(s.equals("😀")){emoji=true;symbols=false;}else if(s.equals("🎙")){mic();}else if(s.equals("⇧")){long n=System.currentTimeMillis();if(n-lastShift<450){caps=!caps;shift=caps;}else shift=!shift;lastShift=n;}else if(s.equals("⌫"))backspace();else if(s.equals("↵"))enter();else if(s.equals("space"))insert(" ");else if(s.equals(",")||s.equals("."))insert(s);else{insert((shift||caps)?s:s.toLowerCase(Locale.ROOT));if(shift&&!caps)shift=false;}invalidate();}
    }
    static class Key{String label;float l,t,r,b;int action;Key(String s,float a,float c,float d,float e,int ac){label=s;l=a;t=c;r=d;b=e;action=ac;}}
}
