plugins { id 'com.android.application' }

android {
    namespace 'com.transvoice.keyboard'
    compileSdk 35
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId 'com.transvoice.keyboard'
        minSdk 23
        targetSdk 35
        versionCode 12
        versionName '1.0.2'
    }
}

dependencies {
    implementation 'com.google.mlkit:translate:17.0.3'
}
